name = "tg-ad-guard-bot"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[vars]
ACTION = "ban"
WARN_THRESHOLD = "3"
ESCALATE_ACTION = "kick"
NEW_MEMBER_GUARD_MINUTES = "10"
ENABLE_PROFILE_HEURISTIC = "true"
NOTIFY_GROUP = "false"
NOTIFY_AUTO_DELETE_SECONDS = "8"

[[kv_namespaces]]
binding = "BOT_KV"
id = "aa82aec00b2240768ed4f75b0ffe5362"
